# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Vivado/projects/CSCI460/arty_linux.cache/wt [current_project]
set_property parent.project_path C:/Vivado/projects/CSCI460/arty_linux.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_output_repo c:/Vivado/projects/CSCI460/arty_linux.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/hdl/arty_microblaze_01_wrapper.vhd
add_files C:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/arty_microblaze_01.bd
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_clk_wiz_0_0/arty_microblaze_01_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_clk_wiz_0_0/arty_microblaze_01_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_clk_wiz_0_0/arty_microblaze_01_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_mig_7series_0_0/arty_microblaze_01_mig_7series_0_0/user_design/constraints/arty_microblaze_01_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_mig_7series_0_0/arty_microblaze_01_mig_7series_0_0/user_design/constraints/arty_microblaze_01_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_microblaze_0_0/arty_microblaze_01_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_microblaze_0_0/arty_microblaze_01_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_microblaze_0_0/arty_microblaze_01_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_dlmb_v10_0/arty_microblaze_01_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_dlmb_v10_0/arty_microblaze_01_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_ilmb_v10_0/arty_microblaze_01_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_ilmb_v10_0/arty_microblaze_01_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_dlmb_bram_if_cntlr_0/arty_microblaze_01_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_ilmb_bram_if_cntlr_0/arty_microblaze_01_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_lmb_bram_0/arty_microblaze_01_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_xbar_0/arty_microblaze_01_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_microblaze_0_axi_intc_0/arty_microblaze_01_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_microblaze_0_axi_intc_0/arty_microblaze_01_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_microblaze_0_axi_intc_0/arty_microblaze_01_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_mdm_1_0/arty_microblaze_01_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_mdm_1_0/arty_microblaze_01_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_rst_mig_7series_0_83M_0/arty_microblaze_01_rst_mig_7series_0_83M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_rst_mig_7series_0_83M_0/arty_microblaze_01_rst_mig_7series_0_83M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_rst_mig_7series_0_83M_0/arty_microblaze_01_rst_mig_7series_0_83M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_ethernetlite_0_0/arty_microblaze_01_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_ethernetlite_0_0/arty_microblaze_01_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_ethernetlite_0_0/arty_microblaze_01_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_ethernetlite_0_0/arty_microblaze_01_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_quad_spi_0_0/arty_microblaze_01_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_quad_spi_0_0/arty_microblaze_01_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_quad_spi_0_0/arty_microblaze_01_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_quad_spi_0_0/arty_microblaze_01_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_gpio_0_0/arty_microblaze_01_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_gpio_0_0/arty_microblaze_01_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_gpio_0_0/arty_microblaze_01_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_gpio_1_0/arty_microblaze_01_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_gpio_1_0/arty_microblaze_01_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_gpio_1_0/arty_microblaze_01_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_uartlite_0_0/arty_microblaze_01_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_uartlite_0_0/arty_microblaze_01_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_uartlite_0_0/arty_microblaze_01_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_timer_0_0/arty_microblaze_01_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_axi_timer_0_0/arty_microblaze_01_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_7/arty_microblaze_01_auto_pc_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_0/arty_microblaze_01_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_0/arty_microblaze_01_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_0/arty_microblaze_01_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_1/arty_microblaze_01_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_1/arty_microblaze_01_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_1/arty_microblaze_01_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_2/arty_microblaze_01_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_2/arty_microblaze_01_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_2/arty_microblaze_01_auto_us_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_0/arty_microblaze_01_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_0/arty_microblaze_01_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_0/arty_microblaze_01_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_0/arty_microblaze_01_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_1/arty_microblaze_01_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_1/arty_microblaze_01_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_1/arty_microblaze_01_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_1/arty_microblaze_01_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_2/arty_microblaze_01_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_2/arty_microblaze_01_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_2/arty_microblaze_01_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_2/arty_microblaze_01_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_3/arty_microblaze_01_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_3/arty_microblaze_01_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_3/arty_microblaze_01_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_3/arty_microblaze_01_auto_pc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_4/arty_microblaze_01_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_4/arty_microblaze_01_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_4/arty_microblaze_01_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_4/arty_microblaze_01_auto_pc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_5/arty_microblaze_01_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_5/arty_microblaze_01_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_5/arty_microblaze_01_auto_ds_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_5/arty_microblaze_01_auto_pc_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_6/arty_microblaze_01_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_6/arty_microblaze_01_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_6/arty_microblaze_01_auto_ds_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_6/arty_microblaze_01_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/arty_microblaze_01_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_microblaze_0_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Vivado/projects/CSCI460/arty_linux.srcs/constrs_1/new/constraints_arty.xdc
set_property used_in_implementation false [get_files C:/Vivado/projects/CSCI460/arty_linux.srcs/constrs_1/new/constraints_arty.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top arty_microblaze_01_wrapper -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef arty_microblaze_01_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file arty_microblaze_01_wrapper_utilization_synth.rpt -pb arty_microblaze_01_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
