# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints_arty.xdc

# Block Designs: bd/arty_microblaze_01/arty_microblaze_01.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01 || ORIG_REF_NAME==arty_microblaze_01} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_clk_wiz_0_0/arty_microblaze_01_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_clk_wiz_0_0 || ORIG_REF_NAME==arty_microblaze_01_clk_wiz_0_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_mig_7series_0_0/arty_microblaze_01_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_mig_7series_0_0 || ORIG_REF_NAME==arty_microblaze_01_mig_7series_0_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_microblaze_0_0/arty_microblaze_01_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_microblaze_0_0 || ORIG_REF_NAME==arty_microblaze_01_microblaze_0_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_dlmb_v10_0/arty_microblaze_01_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_dlmb_v10_0 || ORIG_REF_NAME==arty_microblaze_01_dlmb_v10_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_ilmb_v10_0/arty_microblaze_01_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_ilmb_v10_0 || ORIG_REF_NAME==arty_microblaze_01_ilmb_v10_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_dlmb_bram_if_cntlr_0/arty_microblaze_01_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==arty_microblaze_01_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_ilmb_bram_if_cntlr_0/arty_microblaze_01_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==arty_microblaze_01_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_lmb_bram_0/arty_microblaze_01_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_lmb_bram_0 || ORIG_REF_NAME==arty_microblaze_01_lmb_bram_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_xbar_0/arty_microblaze_01_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_xbar_0 || ORIG_REF_NAME==arty_microblaze_01_xbar_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_microblaze_0_axi_periph_0/arty_microblaze_01_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_microblaze_0_axi_periph_0 || ORIG_REF_NAME==arty_microblaze_01_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_microblaze_0_axi_intc_0/arty_microblaze_01_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_microblaze_0_axi_intc_0 || ORIG_REF_NAME==arty_microblaze_01_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_microblaze_0_xlconcat_0/arty_microblaze_01_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_microblaze_0_xlconcat_0 || ORIG_REF_NAME==arty_microblaze_01_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_mdm_1_0/arty_microblaze_01_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_mdm_1_0 || ORIG_REF_NAME==arty_microblaze_01_mdm_1_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_rst_mig_7series_0_83M_0/arty_microblaze_01_rst_mig_7series_0_83M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==arty_microblaze_01_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_axi_ethernetlite_0_0/arty_microblaze_01_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_axi_ethernetlite_0_0 || ORIG_REF_NAME==arty_microblaze_01_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_axi_quad_spi_0_0/arty_microblaze_01_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_axi_quad_spi_0_0 || ORIG_REF_NAME==arty_microblaze_01_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_axi_gpio_0_0/arty_microblaze_01_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_axi_gpio_0_0 || ORIG_REF_NAME==arty_microblaze_01_axi_gpio_0_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_axi_gpio_1_0/arty_microblaze_01_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_axi_gpio_1_0 || ORIG_REF_NAME==arty_microblaze_01_axi_gpio_1_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_axi_uartlite_0_0/arty_microblaze_01_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_axi_uartlite_0_0 || ORIG_REF_NAME==arty_microblaze_01_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_axi_timer_0_0/arty_microblaze_01_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_axi_timer_0_0 || ORIG_REF_NAME==arty_microblaze_01_axi_timer_0_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_7/arty_microblaze_01_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_pc_7 || ORIG_REF_NAME==arty_microblaze_01_auto_pc_7} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_0/arty_microblaze_01_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_us_0 || ORIG_REF_NAME==arty_microblaze_01_auto_us_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_1/arty_microblaze_01_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_us_1 || ORIG_REF_NAME==arty_microblaze_01_auto_us_1} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_2/arty_microblaze_01_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_us_2 || ORIG_REF_NAME==arty_microblaze_01_auto_us_2} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_0/arty_microblaze_01_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_ds_0 || ORIG_REF_NAME==arty_microblaze_01_auto_ds_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_0/arty_microblaze_01_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_pc_0 || ORIG_REF_NAME==arty_microblaze_01_auto_pc_0} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_1/arty_microblaze_01_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_ds_1 || ORIG_REF_NAME==arty_microblaze_01_auto_ds_1} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_1/arty_microblaze_01_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_pc_1 || ORIG_REF_NAME==arty_microblaze_01_auto_pc_1} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_2/arty_microblaze_01_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_ds_2 || ORIG_REF_NAME==arty_microblaze_01_auto_ds_2} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_2/arty_microblaze_01_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_pc_2 || ORIG_REF_NAME==arty_microblaze_01_auto_pc_2} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_3/arty_microblaze_01_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_ds_3 || ORIG_REF_NAME==arty_microblaze_01_auto_ds_3} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_3/arty_microblaze_01_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_pc_3 || ORIG_REF_NAME==arty_microblaze_01_auto_pc_3} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_4/arty_microblaze_01_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_ds_4 || ORIG_REF_NAME==arty_microblaze_01_auto_ds_4} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_4/arty_microblaze_01_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_pc_4 || ORIG_REF_NAME==arty_microblaze_01_auto_pc_4} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_5/arty_microblaze_01_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_ds_5 || ORIG_REF_NAME==arty_microblaze_01_auto_ds_5} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_5/arty_microblaze_01_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_pc_5 || ORIG_REF_NAME==arty_microblaze_01_auto_pc_5} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_ds_6/arty_microblaze_01_auto_ds_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_ds_6 || ORIG_REF_NAME==arty_microblaze_01_auto_ds_6} -quiet] -quiet

# IP: bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_6/arty_microblaze_01_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_microblaze_01_auto_pc_6 || ORIG_REF_NAME==arty_microblaze_01_auto_pc_6} -quiet] -quiet

# XDC: bd/arty_microblaze_01/arty_microblaze_01_ooc.xdc
