# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_0/arty_microblaze_01_auto_us_0.xci
# IP: The module: 'arty_microblaze_01_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_0/arty_microblaze_01_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_microblaze_01_auto_us_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_0/arty_microblaze_01_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_microblaze_01_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_0/arty_microblaze_01_auto_us_0.xci
# IP: The module: 'arty_microblaze_01_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_0/arty_microblaze_01_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_microblaze_01_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_us_0/arty_microblaze_01_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_microblaze_01_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
