# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_2/arty_microblaze_01_auto_pc_2.xci
# IP: The module: 'arty_microblaze_01_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_2/arty_microblaze_01_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_microblaze_01_auto_pc_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_2/arty_microblaze_01_auto_pc_2.xci
# IP: The module: 'arty_microblaze_01_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado/projects/CSCI460/arty_linux.srcs/sources_1/bd/arty_microblaze_01/ip/arty_microblaze_01_auto_pc_2/arty_microblaze_01_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_microblaze_01_auto_pc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
